CREATE
OR REPLACE TABLE HIRE_VEHICLES_RAW(
    active string,
    vehicle_license_number string,
    name string,
    license_type string,
    expiration_date timestamp,
    permit_license_number string,
    dmv_license_plate_number string,
    vehicle_vin_number string,
    wheelchair_accessible string,
    certification_date timestamp,
    hack_up_date string,
    vehicle_year string,
    base_number string,
    base_name string,
    base_type string,
    veh string,
    base_telephone_number string,
    website string,
    base_address string,
    reason string,
    order_date timestamp,
    last_date_updated timestamp,
    last_time_updated string
);