COPY INTO {table} (
    VendorID,
    lpep_pickup_datetime,
    lpep_dropoff_datetime,
    store_and_fwd_flag,
    RatecodeID,
    PULocationID,
    DOLocationID,
    passenger_count,
    trip_distance,
    fare_amount,
    extra,
    mta_tax,
    tip_amount,
    tolls_amount,
    ehail_fee,
    improvement_surcharge,
    total_amount,
    payment_type,
    trip_type,
    congestion_surcharge
)
FROM(
        SELECT $1 :VendorID::INTEGER AS VendorID,
            TO_TIMESTAMP_NTZ($1 :lpep_pickup_datetime::VARCHAR) AS lpep_pickup_datetime,
            TO_TIMESTAMP_NTZ($1 :lpep_dropoff_datetime::VARCHAR) AS lpep_dropoff_datetime,
            $1 :store_and_fwd_flag::STRING AS store_and_fwd_flag,
            $1 :RatecodeID::INT AS RatecodeID,
            $1 :PULocationID::INT AS PULocationID,
            $1 :DOLocationID::INT AS DOLocationID,
            $1 :passenger_count::INT AS passenger_count,
            $1 :trip_distance::FLOAT AS trip_distance,
            $1 :fare_amount::FLOAT AS fare_amount,
            $1 :extra::FLOAT AS extra,
            $1 :mta_tax::FLOAT AS mta_tax,
            $1 :tip_amount::FLOAT AS tip_amount,
            $1 :tolls_amount::FLOAT AS tolls_amount,
            $1 :ehail_fee::INT AS ehail_fee,
            $1 :improvement_surcharge::FLOAT AS improvement_surcharge,
            $1 :total_amount::FLOAT AS total_amount,
            $1 :payment_type::INT AS payment_type,
            $1 :trip_type::INT AS trip_type,
            $1 :congestion_surcharge::FLOAT AS congestion_surcharg
        FROM @{stage_name}
    );